### ISSUE TITLE
Expose file size

### ISSUE THREAD

**Issue by focusaurus** [iredelmeier/filesystem-rs#1]
Would you consider exposing either all of the `std::fs::Metadata` trait or at least the size? At the moment I can't effectively use this crate because I need to read partial files and also want to know total file size without reading the entire file. But otherwise the overall idea and approach is exactly what I am looking for.

**Comment by focusaurus** [comment]
Just a note that I'm using the `rsfs` crate at the moment which provides permissions and file size.

**Comment by iredelmeier** [comment]
Sorry for the belated response!

There is now [`len`](https://docs.rs/filesystem/0.4.2/filesystem/trait.FileSystem.html#tymethod.len), which will tell you the size of a file. Is that sufficient for your use case? I can also investigate adding a `Metadata` trait and/or a method that corresponds to [`std::io::Read::read_exact`](https://doc.rust-lang.org/std/io/trait.Read.html#method.read_exact).

**Comment by focusaurus** [comment]
No worries. My [current rsfs-based code](https://github.com/focusaurus/tealeaves/blob/33b890f7395c8a4027e4d5e4b20dd57136cb42ab/src/lib.rs#L39) uses the length as well as the permissions.
