### ISSUE TITLE
Renaming directories doesn't always work

### ISSUE THREAD

**Issue by gavynriebau** [iredelmeier/filesystem-rs#2]
Hi @iredelmeier,

Firstly would like to say I really like the project, appreciate the work you've already put into it so far and am looking forward to making use of it in some of my own projects.

I've found that the `FakeFileSystem.rename` function doesn't consistently work in a test that I've written.
The test uses the `rename` function on multiple files/directories and, when run with `cargo test`, it sometimes passes but sometimes fails even without any code modifications between subsequent runs.
To try to help I've extracted the minimum code to replicate the bug into [an example repository here](https://github.com/gavynriebau/filesystem_race_condition_bug).

I'm new to rust programming so apologies if the fault is with my code but I'd really appreciate if you were to take a look at the example code I linked and let me know whether you think this is a legitimate bug or just some mistake I've made.

**Comment by iredelmeier** [comment]
Thanks for noticing @gavynriebau, and for the super helpful replication repo! Also, welcome to Rust :)

It's definitely a bug in the library, not your code - should be fixed by #4. I'll publish a new version tonight.

**Comment by gavynriebau** [comment]
@iredelmeier you fixed this so fast!
Thanks for taking the time to look into this :+1:
